authors:
  ianderrington:
    name: Ian Derrington 
    description: >
      Ian Derrington is a software engineer and writer. He is the creator of Gen()AI, a platform for enabling AI to be understood, and used, by people and Gen()AI.
    avatar: https://ianderrington.com/assets/i_logo.png